name: 'Lava CI Setup'
description: 'Setup environment for CI run in Lava repositories'
inputs:
  repository:
    description: 'repository name'
    required: false
    default: 'lava'
runs:
  using: "composite"
  steps:        
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
  
    - name: Install Poetry
      run: | 
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install pipx      
        python3.9 -m pipx install poetry==1.4.2
        python3.9 -m pipx ensurepath
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction --no-root
      shell: bash

    - name: Install Lava
      run: poetry install --no-interaction
      shell: bash
